// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwUGlz9fViOl0GpnduPOlrxM8yyqiWrnE',
    appId: '1:719915750705:web:0648ff0f0b7600f9480c10',
    messagingSenderId: '719915750705',
    projectId: 'pfeproject-c8881',
    authDomain: 'pfeproject-c8881.firebaseapp.com',
    storageBucket: 'pfeproject-c8881.appspot.com',
    measurementId: 'G-ZMJHRJDPE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdPUs215rG5WZ5GGlzav2ewktAVUrzzCY',
    appId: '1:719915750705:android:4acd405e2aeb8989480c10',
    messagingSenderId: '719915750705',
    projectId: 'pfeproject-c8881',
    storageBucket: 'pfeproject-c8881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KbYslVRQAZjBu0UT2iVC0N3mfSe7wjc',
    appId: '1:719915750705:ios:437e0c1a52e2b014480c10',
    messagingSenderId: '719915750705',
    projectId: 'pfeproject-c8881',
    storageBucket: 'pfeproject-c8881.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KbYslVRQAZjBu0UT2iVC0N3mfSe7wjc',
    appId: '1:719915750705:ios:437e0c1a52e2b014480c10',
    messagingSenderId: '719915750705',
    projectId: 'pfeproject-c8881',
    storageBucket: 'pfeproject-c8881.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwUGlz9fViOl0GpnduPOlrxM8yyqiWrnE',
    appId: '1:719915750705:web:7c859272818164a2480c10',
    messagingSenderId: '719915750705',
    projectId: 'pfeproject-c8881',
    authDomain: 'pfeproject-c8881.firebaseapp.com',
    storageBucket: 'pfeproject-c8881.appspot.com',
    measurementId: 'G-FS7QLKJMPX',
  );
}
